### ISSUE TITLE
Filament bends instead of cuts 

### ISSUE THREAD

**Issue by f00d4tehg0dz** [kevinakasam/ERCF_Filament_Cutter#29]
Most of the time, the filament bends instead of getting a forceable cut.  I noticed quite a bit of flex with the mount as well. Perhaps user error on my part? I'm using Beta 7 on an ERCF 1.1 Klipper 11 with Happy-Hare. 

Here is my config

```
# These variables control the servo movement
variable_servo_closed_angle   : 5	; Servo angle for closed postion with bowden aligned MMU
variable_servo_open_angle     : 180 ; Servo angle to open up the cutter and move bowden away from MMU
variable_servo_duration       : 0.4	; Time (s) of PWM pulse to activate servo
variable_servo_idle_time      : 1.0	; Time (s) to let the servo to reach it's position

# Controls for feed and cut lengths
variable_feed_length          : 58	; Distance in mm from gate parking position to blade (ERCFv1.1: 58, v2/other: 48)
variable_cut_length           : 10	; Amount in mm of filament to cut
variable_cut_attempts         : 3	; Number of times the cutter tries to cut the filament```

**Comment by Blendan1** [comment]
I have had the same issue before, what solved it for me was not using PTFE tubing on the encoder.

It seems that the extra squishyness of the tube allows the filament to bend, but when it directly presses against the pla it cuts.

Maybe a design change could be that a second knife, that's mounted on the encoder so that's more like a scissor.
